/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fase3;

/**
 *
 * @author Rafael
 */
public class BuscaRotulos extends javax.swing.JFrame {

    /**
     * Creates new form BuscaRotulos
     */
    public BuscaRotulos() {
        initComponents();
        listaImagens = new ListaImagens();
        arquivo = new Arquivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaImagensComRotulo = new javax.swing.JList<>();
        buscaAnotacoes = new javax.swing.JTextField();
        jButtonBuscaAnotacoes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listInstantSearch = new javax.swing.JList();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        inicioBuscaRotulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaImagensComRotulo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaImagensComRotulo);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, 170));

        buscaAnotacoes.setPreferredSize(new java.awt.Dimension(200, 28));
        buscaAnotacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscaAnotacoesKeyReleased(evt);
            }
        });
        jPanel1.add(buscaAnotacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, -1));

        jButtonBuscaAnotacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buscar2.png"))); // NOI18N
        jButtonBuscaAnotacoes.setFocusable(false);
        jButtonBuscaAnotacoes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscaAnotacoes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBuscaAnotacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaAnotacoesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscaAnotacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jScrollPane1.setBorder(null);

        listInstantSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listInstantSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listInstantSearch);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 110));

        jTabbedPane1.addTab("Busca de Rótulos", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 230, -1));
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 570, 620));

        inicioBuscaRotulo.setText("Busca de Rótulos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(18, Short.MAX_VALUE)
                    .addComponent(inicioBuscaRotulo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(28, Short.MAX_VALUE)
                    .addComponent(inicioBuscaRotulo)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 70));

        jButton1.setText("Abrir Projeto");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonBuscaAnotacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaAnotacoesActionPerformed

    }//GEN-LAST:event_jButtonBuscaAnotacoesActionPerformed

    private void listInstantSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listInstantSearchMouseClicked

    }//GEN-LAST:event_listInstantSearchMouseClicked

    private void buscaAnotacoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaAnotacoesKeyReleased

    }//GEN-LAST:event_buscaAnotacoesKeyReleased
    private ListaImagens listaImagens;
    private Arquivo arquivo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscaAnotacoes;
    private javax.swing.JLabel inicioBuscaRotulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscaAnotacoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JList listInstantSearch;
    private javax.swing.JList<String> listaImagensComRotulo;
    // End of variables declaration//GEN-END:variables
}
